name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Database
  DATABASE_USER: ${{ github.repository_owner }}_user
  DATABASE_PASSWORD: ${{ github.sha }}_db_pass
  DATABASE_NAME: app_db_${{ github.ref_name }}
  DATABASE_HOST: database
  DATABASE_PORT: 5432
  
  # Redis
  REDIS_HOST: redis_server
  REDIS_PORT: 6379
  REDIS_PASSWORD: ${{ github.sha }}_redis
  
  # FastAPI
  API_KEY: api_${{ github.sha }}_key
  JWT_SECRET_KEY: ${{ github.sha }}_jwt_secret
  JWT_ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 30
  
  # Next.js
  NEXT_PUBLIC_API_URL: http://fastapi_server:8000
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: ${{ github.sha }}_next_secret
  GITHUB_ID: dummy_github_id_123
  GITHUB_SECRET: dummy_github_secret_456
  
  # Grafana
  GF_SECURITY_ADMIN_USER: admin_${{ github.ref_name }}
  GF_SECURITY_ADMIN_PASSWORD: ${{ github.sha }}_grafana
  
  # Caddy
  EXT_ENDPOINT1: https://api.example.com
  LOCAL_1: http://fastapi_server:8000
  LOCAL_2: http://nextjs_server:3000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Install Docker Compose
      run: |
        curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
      
    - name: Set up environment files
      run: |
        # Main .env file
        cat << EOF > .env
        DATABASE_USER=$DATABASE_USER
        DATABASE_PASSWORD=$DATABASE_PASSWORD
        DATABASE_NAME=$DATABASE_NAME
        DATABASE_HOST=$DATABASE_HOST
        DATABASE_PORT=$DATABASE_PORT
        REDIS_HOST=$REDIS_HOST
        REDIS_PORT=$REDIS_PORT
        REDIS_PASSWORD=$REDIS_PASSWORD
        API_KEY=$API_KEY
        JWT_SECRET_KEY=$JWT_SECRET_KEY
        JWT_ALGORITHM=$JWT_ALGORITHM
        ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
        EOF
        
        # Frontend .env file
        cat << EOF > frontend/.env
        NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
        NEXTAUTH_URL=$NEXTAUTH_URL
        NEXTAUTH_SECRET=$NEXTAUTH_SECRET
        GITHUB_ID=$GITHUB_ID
        GITHUB_SECRET=$GITHUB_SECRET
        EOF

    - name: Build and start containers
      run: |
        docker-compose build
        docker-compose up -d

    - name: Run tests
      run: |
        echo "Running tests..."
        # Ajoutez vos commandes de test ici

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production..."
        # Ajoutez vos commandes de déploiement ici