name: Release Rules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  dont-run-if-release:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping as this is not a release"

  dont-run-if-release-on-version:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Version
        run: echo "Skipping as this is not a version tag"

  dont-run-if-not-mr:
    if: ${{ !github.event.pull_request && github.event.before != '0000000000000000000000000000000000000000' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping as this is not a PR"

  dont-run-if-post-merge:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping post-merge job"

  run-if-post-merge:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Post Merge Actions
        run: echo "Running post-merge tasks"

  run-only-for-merge-request:
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: PR Checks
        run: |
          echo "Running PR specific tasks"
          # Add your PR specific tasks here